Do not remove args

diff --git a/apache-maven/src/assembly/maven/bin/mvn b/apache-maven/src/assembly/maven/bin/mvn
--- a/apache-maven/src/assembly/maven/bin/mvn
+++ b/apache-maven/src/assembly/maven/bin/mvn
@@ -180,37 +180,34 @@ if $cygwin || $mingw ; then
   MAVEN_PROJECTBASEDIR=`cygpath --windows "$MAVEN_PROJECTBASEDIR"`
 fi
 
-args=""
-while [ $# -gt 0 ]; do
-  case $1 in
-    --debug)
-      if [ -z "$MAVEN_DEBUG_OPTS" ] ; then
-        MAVEN_DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=${MAVEN_DEBUG_ADDRESS:-localhost:8000}"
-      else
-        echo "Ignoring --debug option as MAVEN_DEBUG_OPTS is already set"
-      fi
-      ;;
-    --yjp)
-      if [ ! -f "$YJPLIB" ]; then
-        echo "Error: Unable to autodetect the YJP library location. Please set YJPLIB variable" >&2
-        exit 1
-      fi
-      MAVEN_OPTS="-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal $MAVEN_OPTS"
-      ;;
-    --enc)
-      MAVEN_MAIN_CLASS="org.apache.maven.cling.MavenEncCling"
-      ;;
-    *)
-      if [ -z "$args" ]; then
-        args="\"$1\""
-      else
-        args="$args \"$1\""
-      fi
-      ;;
-  esac
-  shift
-done
+handle_args() {
+  while [ $# -gt 0 ]; do
+    case $1 in
+      --debug)
+        if [ -z "$MAVEN_DEBUG_OPTS" ] ; then
+          MAVEN_DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=${MAVEN_DEBUG_ADDRESS:-localhost:8000}"
+        else
+          echo "Ignoring --debug option as MAVEN_DEBUG_OPTS is already set"
+        fi
+        ;;
+      --yjp)
+        if [ ! -f "$YJPLIB" ]; then
+          echo "Error: Unable to autodetect the YJP library location. Please set YJPLIB variable" >&2
+          exit 1
+        fi
+        MAVEN_OPTS="-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal $MAVEN_OPTS"
+        ;;
+      --enc)
+        MAVEN_MAIN_CLASS="org.apache.maven.cling.MavenEncCling"
+        ;;
+      *)
+        ;;
+    esac
+    shift
+  done
+}
 
+handle_args "$@"
 MAVEN_MAIN_CLASS=${MAVEN_MAIN_CLASS:=org.apache.maven.cling.MavenCling}
 
 exec "$JAVACMD" \
@@ -225,4 +222,4 @@ exec "$JAVACMD" \
   "-Dmaven.multiModuleProjectDirectory=$MAVEN_PROJECTBASEDIR" \
   $LAUNCHER_CLASS \
   $MAVEN_ARGS \
-  $args
+  "$@"
